FROM <%= image.vars['source_image'] %>:<%= image.version %>

<%= snippet('labels', binding) -%>

ENV TZ America/Vancouver
ENV RUNUSER none
ENV HOME /

<%= snippet('docker-entrypoint', binding) -%>



<%= snippet('dockerize', binding) -%>



<%= snippet('tini', binding) -%>

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD [ "init-loop" ]
