FROM <%= image.vars['source_image'] %>:<%= image.version %>

<%= snippet('labels', binding) -%>

ENV TZ America/Vancouver
ENV RUNUSER none
ENV HOME /

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD [ "init-loop" ]

<% if image.variant == 'supervisord' -%>
RUN yum -y install epel-release

# Install & configure supervisor
RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
        supervisor \
 && mkdir -p /etc/supervisor/conf.d
COPY supervisor.conf /etc/supervisor.conf

CMD ["supervisord", "-c", "/etc/supervisor.conf"]
<% end -%>
